# Generated by Django 3.1.7 on 2021-03-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='backorder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='downstream_player',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='instructors',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='upstream_player',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
