# Generated by Django 3.1.7 on 2021-03-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('role', models.CharField(max_length=15)),
                ('demand', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('inventory', models.IntegerField()),
            ],
        ),
    ]
